### ISSUE TITLE
Work with mvnvm

### ISSUE THREAD

**Issue by davidmankin** [jcgay/homebrew-jcgay#3]
It'd be great if there was a way for maven-deluxe to work with [mvnvm](mvnvm.org) so that I could still get colored maven output when using mvnvm.  I don't understand all the tool A calls tool B details yet to suggest how this would work, though.  Hopefully someone else does?

**Comment by jcgay** [comment]
I don't use `mvnvm` but it seems that this tool download a Maven distribution for you ? 
Maybe you can set a custom URL to download a `mvn` archive ?

**Comment by gjoseph** [comment]
mvnvm will download a maven version that it doesn't know about yet. Basic usage is to have a `mvnvm.properties` file in your project that contains e.g `mvn_version=3.3.9`. The versions it knows about are stored under `~/.mvnvm/` by default. It feels like maven-deluxe would need to be reinstalled after every new version of maven gets used/downloaded by mvnvm. But then again, it looks like it's also the case if I have a single maven and update it via brew, unless the dependency tells brew "reinstall me when mvn gets updated" ?

**Comment by jcgay** [comment]
The brew formula duplicates Maven installation. So that you can have a vanilla `mvn` installed next to a `maven-deluxe` one. So if you link `mvn` to `maven-deluxe`, updates are handled by `brew`.

I don't see a way to integrate with `mvnvm` (as you have pointed out @gjoseph) except to write a script which applies `maven-color` installation steps to all `mvn` installation managed by `mvnvm`. It seems that @davidmankin has done just that at: https://bitbucket.org/snippets/atlassian/96rn9/maven-color-with-mvnvm 👍

**Comment by jcgay** [comment]
Feel free to re-open if it's still actual.

**Comment by gjoseph** [comment]
I don't think this is still relevant, no, since Maven now has native colour support ;)
